"""create description to Expense

Revision ID: b1d706fdee43
Revises: 3665ecec0903
Create Date: 2026-01-13 13:17:46.459893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d706fdee43'
down_revision: Union[str, Sequence[str], None] = '3665ecec0903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'description')
    # ### end Alembic commands ###
